export const ArticleConst = {
  ARTICLE_LOADING: "ARTICLE_LOADING",
  ON_FAIL: "ON_FAIL",
  ON_SUCCESS: "ON_SUCCESS",
  ADD_ARTICLE: "ADD_ARTICLE",
  REST_ARTICLE: "REST_ARTICLE",
  UPDATE_ARTICLE: "UPDATE_ARTICLE",
  REMOVE_ARTICLE: "REMOVE_ARTICLE",
  ONERROR: "ONERROR",
};
